name: Cypress Shop Pipe
on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - Ubuntu
        - macOS


jobs:
  first_job:
    runs-on: [self-hosted, "${{ inputs.chosen-os }}"]
    steps: 
      - run: ls